server:
  port: 8005
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service:8002
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://product-service:8001
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://shopping-service:8003
          predicates:
            - Path=/invoices/**
