server:
  port: 9999
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service:8002
          predicates:
            - Path=/customers/**
